# language: c
# matrix:
#   include:
#     - os: osx
#     osx_image: xcode8
#     env:
#       - MATRIX_EVAL="brew install gcc && CC=gcc-7"
#     compiler: gcc
#     script: make all

# before_install:
#   - eval "${MATRIX_EVAL}"

language: c
# os: osx
# osx_image: xcode8
# before_install: eval "brew install gcc"
script: make all